version: '3.8'

services:
  # The Neo4j Database Service
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data:/data
      - ./plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/password

  # The Python Application Service
  app:
    build: .  # Build the image from the Dockerfile in the current directory
    depends_on:
      - neo4j # Ensures Neo4j starts before the Python app tries to connect
    environment:
      # Pass connection details to the Python script
      # IMPORTANT: The hostname is 'neo4j', the service name, not 'localhost'
      - NEO4J_URI=neo4j://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
